### ISSUE TITLE
DoH (wireformat) throws exception when decoding HTTP request body

### ISSUE THREAD

**Issue by I-Knight-I** [lsongdev/node-dns#85]
The following `readStream` function is the culprit:
https://github.com/song940/node-dns/blob/b2fdf66a1987e2597ad1b1f0948d0ac5c4acbfe2/server/doh.js#L22-L28

It's initialising the buffer as a string and not converting it for the `resolve()` call.
It should be:

```js
const readStream = stream => new Promise((resolve, reject) => {
  let buffer = '';
  stream
    .on('error', reject)
    .on('data', chunk => { buffer += chunk; })
    .on('end', () => resolve(Buffer.from(buffer)));
});
```

**Comment by lsongdev** [comment]
fix
